/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bot2;

import javax.security.auth.login.LoginException;

import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.OnlineStatus;
import net.dv8tion.jda.api.entities.Activity;

public class App {
    public static void main(String[] args) throws LoginException{
        JDABuilder jda = JDABuilder.createDefault("OTQ1Nzg3MDg5NDIzODI2OTc0.YhVO3Q.QyWcToDsbo3N12Zm3jNFhnGRB5g");
        jda.setActivity(Activity.watching("Hej"));
        jda.setStatus(OnlineStatus.ONLINE);
        jda.addEventListeners(new MayBot());
        jda.build();
    }
}

